### ISSUE TITLE
does not work for teamviewer

### ISSUE THREAD

**Issue by mailinglists35** [sandwichdoge/MinimizeToTray#1]
download tv 15
open the installer, select run instead of install
press alt-f1

results: window is immune
expected results: window hides

**Comment by sandwichdoge** [comment]
Looks like TeamViewer intentionally disables any attempt at modifying its GUI state, including making it hidden.  Probably to prevent malicious usage of their software.
MinimizeToTray only works on compliant Windows GUIs. 
A workaround would be to modify the target application's memory directly, but that'd be against plenty of software TOS.
