### ISSUE TITLE
Option to set focus to window on restore

### ISSUE THREAD

**Issue by FusionX9000** [sandwichdoge/MinimizeToTray#10]
I think it would be useful if there was an option to set focus to the last restored window. 

I've no knowledge of AutoIt so I won't do a pull request but adding a WinActivate function after the restore seems to work.

**Comment by sandwichdoge** [comment]
Yes that should work. I will add this feature this weekend.

**Comment by sandwichdoge** [comment]
I added the feature.
https://github.com/sandwichdoge/MinimizeToTray/commit/cd1c736af31ce81ede503234e6c302258ba8b96e
