### ISSUE TITLE
new version of xlrd will fail to update language

### ISSUE THREAD

**Issue by wong8888** [sandwichdoge/MinimizeToTray#15]
new version of xlrd will fail to update language

after i search new version(2.0.1) will fail load for xlsx file, need use 1.2.0 for work.

(P.S.: 1.2.0 is least work for my case)

**Comment by sandwichdoge** [comment]
I specified xlrd version in this commit:
https://github.com/sandwichdoge/MinimizeToTray/commit/605634a6e5c0026ed5225815a8e969a512536ef5
