### ISSUE TITLE
[Feature Request] Hide items in System Tray

### ISSUE THREAD

**Issue by Aktimoose** [sandwichdoge/MinimizeToTray#16]
A feature I've been wanting from a program is being able to hide things already inside the "hidden icons" menu in the system tray, and I think it would fit MinimizeToTray as it already does this with windows. I'd like the ability to completely hide the Windows Defender's or any other programs' icon to minimise on the amount of things clogging up my system tray.

I'd like to be able to go from
![image](https://user-images.githubusercontent.com/44620677/131222428-267ee538-2242-48ab-ba9e-f3cf0dabbd96.png)
to
![image](https://user-images.githubusercontent.com/44620677/131222432-9fa5904c-3f5b-4270-8cdb-4e194eeb7716.png)
without having to actually close any of these programs.

**Comment by Wrighty0161** [comment]
You can already do this in windows. 

RIght click the taskbar > taskbar settings > Scroll down to NOTIFICATION AREA and click "Select which icons appear on the taskbar" and turn off Windows Defender (Windows Security notification icon)

**Comment by Aktimoose** [comment]
> 
> 
> You can already do this in windows.
> 
> RIght click the taskbar > taskbar settings > Scroll down to NOTIFICATION AREA and click "Select which icons appear on the taskbar" and turn off Windows Defender (Windows Security notification icon)

That simply just puts it in the overflow area
![image](https://user-images.githubusercontent.com/44620677/134704661-7ad5caee-a183-4173-ae34-c0572f3b608d.png)
