### ISSUE TITLE
ALT+F1 not working for command prompt

### ISSUE THREAD

**Issue by hikarulin** [sandwichdoge/MinimizeToTray#17]
I have a program(exe) to offer some http service, it's ugly to show command prompt window.
I want to hide command prompt window, but it seems MinimizeToTray do not support this?

**Comment by hikarulin** [comment]
Correct:
It's weird that it works sometimes for command prompt. But I have no idea how to reproduce it

**Comment by sandwichdoge** [comment]
If you run the Command Prompt as Administrator, you need to run MinimizeToTray as Administrator as well.
