### ISSUE TITLE
The app deletes itself

### ISSUE THREAD

**Issue by Budgie2108** [sandwichdoge/MinimizeToTray#18]
When I launch the app it automatically deletes itself and the files it uses. This happened when I updated it to v2.4. In previous versions there was no problems. 

Windows 11 Insider edition.

**Comment by FibreFoX** [comment]
Have you checked Windows Defender/Security, if it is (falsly) detected as malicious software and then removed?

**Comment by RobDaMob** [comment]
oh it was falsely detected
