### ISSUE TITLE
Not hiding the WhatsApp icon from the taskbar after the recent WhatsApp update

### ISSUE THREAD

**Issue by Mutahhar** [sandwichdoge/MinimizeToTray#19]
I recently installed new Windows updates, and WhatsApp for Windows was updated as well. Following the recent WhatsApp update, MinimizeToTray no longer hides the WhatsApp icon from the taskbar. It does, however, successfully hide the WhatsApp window.

MinimizeToTray version 2.4

**Comment by LoganDark** [comment]
> Following the recent WhatsApp update, MinimizeToTray no longer hides the WhatsApp icon from the taskbar.

Tray icons aren't windows
