### ISSUE TITLE
Function keys do not work

### ISSUE THREAD

**Issue by ineuw** [sandwichdoge/MinimizeToTray#2]
Softwareloads, but Alt-F1, Alt-F2 and  Shift-Esc do not function and nothing gets minimized to the tray.  Is this app development abandoned?

**Comment by sandwichdoge** [comment]
This happens if another app is holding the keys hostage, or something on your Windows prevents AutoIt from binding to the hotkeys (could be antivirus).
You can try minimizing other different applications and tell me the result.

**Comment by ineuw** [comment]
Thanks for the speedy reply. It was not antivirus. Autolt conflicts with AutoHotkey which was loaded, even though the keys are not used in my .ahk file. Once AHK was closed, Alt-f1 and Alt-f2 functioned. Sadly, this makes MTT unusable My work relies on AHK. Then, if this is solved, there is no icon of the minimized app in the system tray. Without it, the user flies blind.

**Comment by sandwichdoge** [comment]
I'll see if I can add some sort of config so we can change the hotkey to some other combinations than Alt-F1 and Alt-F2.

**Comment by sandwichdoge** [comment]
You can try v2.0. I added a GUI to customize the hotkeys.

**Comment by ineuw** [comment]
Much thanks for your help. If there is an additional issue, I will post it.

**Comment by Neurotoxin001** [comment]
> there is no icon of the minimized app in the system tray. Without it, the user flies blind.

I using 2.4 and there is still no icons of hidden programs in tray (I minimize Google Chrome and Photoshop). Even when I run it as admin on Windows 10 LTSC (1809).
