### ISSUE TITLE
Language_Load_Error

### ISSUE THREAD

**Issue by tloc241** [sandwichdoge/MinimizeToTray#22]
I try to auto-run this using task scheduler and this happen
![bug 1](https://github.com/sandwichdoge/MinimizeToTray/assets/112869206/1476fff0-d71f-4cb9-b8a4-95cd915ba496)
![bug2](https://github.com/sandwichdoge/MinimizeToTray/assets/112869206/aee4a378-ff2b-4219-84ef-d32d1d336a1a)
can anyone know how to fix this issue?

**Comment by henriquedesousa** [comment]
Yes. Create a shortcut to the .exe file and execute it from the shortcut.
