### ISSUE TITLE
Command line feature ?

### ISSUE THREAD

**Issue by Catarax** [sandwichdoge/MinimizeToTray#3]
Hello,
Is there a command line feature in order to hide a particular exe running ?
Thank you!

**Comment by sandwichdoge** [comment]
Not at the moment, but I can add that feature. What do you have in mind? cmdline to hide currently active window, based on process name?

**Comment by Catarax** [comment]
Yes that's it!
A cmdline for hiding a software, process name would be great or the complete path of the exe (like C:\...\software.exe), it's good too.
Thanks!

**Comment by sandwichdoge** [comment]
You can check v2.
- We may now run MTT in command line mode. This mode is completely different from GUI mode. Intended to be run once.
- Example hiding all windows created by the process firefox.exe and its child threads:
```
./MinimizeToTray.exe -p firefox.exe -H
```

**Comment by Catarax** [comment]
Thanks a lot!

**Comment by sandwichdoge** [comment]
@Catarax You can run it with -h opt to show all possible arguments. I forgot to add that in the notes.
