### ISSUE TITLE
Past Application Additions Kept Even after complete Shutdown

### ISSUE THREAD

**Issue by dbareis** [sandwichdoge/MinimizeToTray#5]
The picture below shows MinimizeToTray's menu after a complete shutdown & restart and using ALT+F1 once.  It looks like it's kept 28 from the last 28 restarts.

It's version 2.1, took me a while to work out how to find that, you should have an "About" option which includes anything you'd like to know.

![MinimizeToTray](https://user-images.githubusercontent.com/295230/98869594-25b9f300-24c6-11eb-85ff-ca110f990322.png)

**Comment by sandwichdoge** [comment]
You can try enabling this option: Extra -> Restore hidden windows on Exit.

**Comment by dbareis** [comment]
Thanks that option may help and I already set that, if the program it is not already running (to allow for command line usage) then it should clear the list on startup.  Or maybe less work, if no command line on invokation then clear the list and add a command-line option to clear the list.

**Comment by sandwichdoge** [comment]
The Legacy windows is actually a feature. In case the user accidentally kills MinimizeToTray, we need something for them to restore the previously hidden windows.
I can add an option to not keep legacy windows.

**Comment by dbareis** [comment]
By kill you mean close?  On close it should restore all windows.

**Comment by sandwichdoge** [comment]
Kill is when MTT process gets terminated by external means (e.g. the Task Manager), instead of right-clicking on the tray icon -> Exit.

**Comment by sandwichdoge** [comment]
You can check v2.3. Legacy windows are turned off by default now.
