### ISSUE TITLE
HotKey GUI doesn't allow for None

### ISSUE THREAD

**Issue by dbareis** [sandwichdoge/MinimizeToTray#6]
RE: https://github.com/sandwichdoge/MinimizeToTray/issues/2

It seems to me that if the app can't bind to a hotkey then a message should be displayed.

Other than that I just noticed that "Restore all hidden Windows" is bound to F10, I don't want the key hijacked and I don't plan on using that function so I tried "None" but the app reports "HotKeys must not be empty".  If the tray menu provides the function you should not force the user to use hotkeys other than for "Hide active Window" (as focus lost).

**Comment by sandwichdoge** [comment]
Alright makes sense, I'll look into it. Though the hotkey to hide windows can't be empty.

**Comment by sandwichdoge** [comment]
Hotkeys for "Restore all hidden Windows" and "Restore last hidden window" in Editor maybe None/Empty.
https://github.com/sandwichdoge/MinimizeToTray/commit/81e3879b0526c198ca2bb984ab6c9c5b0b62b295
