### ISSUE TITLE
MinimizeToTray crash when  open  chrome   built-in   task manager

### ISSUE THREAD

**Issue by liang-chang** [sandwichdoge/MinimizeToTray#7]
OS：windows 7 professional  x64
MinimizeToTray  version ：2.2

step 1.  open chrome with a tab A
step 2.  open a new tab B and draw it to a new single window , connect a site like youtube
step 3.  alt + f1 to hide tab B youtube window
step 4.  switch to  tab A use shift + esc open chrome built-in   task manager

now you will see MinimizeToTray has gone .

**Comment by sandwichdoge** [comment]
Shift+Esc is the hotkey to exit MTT right now. I will remove it in the future.

**Comment by sandwichdoge** [comment]
> 
> 
> Shift+Esc is the hotkey to exit MTT right now. I will remove it in the future.

You can check v2.3. I removed the Shift+Esc hotkey.
