### ISSUE TITLE
Multilingual support

### ISSUE THREAD

**Issue by TitusKirch** [sandwichdoge/MinimizeToTray#8]
I would suggest to outsource texts in extra language files. Depending on the system language, these should then be loaded and displayed to the user (you might want to add an extra option here if the user wants to use a different language for the program). Moreover, English would still make sense as a fallback language.

I could help with the translation into German.

**Comment by sandwichdoge** [comment]
I'll come up something for easy language contribution.

**Comment by sandwichdoge** [comment]
You can clone from the latest commit on master, edit Excel file language_gen/language_gen.xlsx, then add texts to the German column. After that open a PR, I'll merge.

**Comment by TitusKirch** [comment]
All right, I will do this later today.

**Comment by TitusKirch** [comment]
Check #11

**Comment by sandwichdoge** [comment]
Thanks commits merged, I will add an option to select language soon.

**Comment by sandwichdoge** [comment]
Added support for language selection:
https://github.com/sandwichdoge/MinimizeToTray/commit/a584604cb8a6ac207cea743126b814b4dbb9263f
