### ISSUE TITLE
Option: Start programme on start-up

### ISSUE THREAD

**Issue by TitusKirch** [sandwichdoge/MinimizeToTray#9]
I think the title says it all. But briefly why: It is easier for the user than to put the program into the autostart.

**Comment by sandwichdoge** [comment]
To do that requires messing with Windows Registry. Honestly I'd rather not do that because of compatibility issues. But if someone can get it to work as well as test and maintain it in the long run, I'll accept their PRs.

**Comment by smaragdus** [comment]
I prefer [MinimizeToTray](https://github.com/sandwichdoge/MinimizeToTray) to stay fully portable as it is now- all settings saved in configuration file (`MTTconf.ini`) inside program folder.

**Comment by githerit** [comment]
Found a solution for myself. The program starts immediately minimized to the tray. To do this, I added the **start /min** argument to startup.
The full version of the registry key looks like this:
`"C:\Program Files\Minimize to Tray\Minimize2Tray.exe" start /min`

**Comment by Tasid47** [comment]
You can simply put a shortcut of the minimizetotray.exe in the windows startup folder which you can get to by typing shell:startup in the run dialog by pressing Windows Key + R
